# Generated by Django 4.1.3 on 2022-11-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(default='Guest', max_length=244, null=True)),
                ('title', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
